spring.application.name=financeApp

# 1. Database Connection URL (Change 'finance_db' to your actual database name)
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:finance_db}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=true

# 2. Database Credentials
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:Sam123@$?}

# 3. Driver Class (Spring Boot usually auto-detects this, but it's safer to include)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwtKey=${JWT_SECRET:cWiWjvM6pyUCQs692BjDTgYheEJBiXsxlLGJryDnn+s=}
